#  инструкция для GitHub Actions

name: Run Tests                    # Название пайплайна (видно во вкладке Actions)

on:
  push:
    branches: [main]               # Запускать при пуше в ветку main
  pull_request:
    branches: [main]               # Запускать при создании PR в main

jobs:
  test:
    runs-on: ubuntu-latest         # Виртуальная машина с Ubuntu
    steps:
      - name: Checkout code        # Шаг 1: скачать код из репозитория
        uses: actions/checkout@v4

      - name: Build Docker image   # Шаг 2: собрать Docker-образ с тестами
        run: docker build -t cart-tests .

      - name: Run tests            # Шаг 3: запустить контейнер с тестами
        run: docker run cart-tests -v -m "not slow"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR
        run: |
          docker tag cart-tests ghcr.io/irrlanska/pytest-playground:latest
          docker push ghcr.io/irrlanska/pytest-playground:latest